import { Inter } from "next/font/google";
import "./globals.css";
import Button from "./button/page.js"
import { ClerkProvider, UserButton } from '@clerk/nextjs'
import Link from 'next/link';
import Home from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body className={inter.className}>
          <nav>
          <Link href="/sign-up">Sign-Up</Link>  |  <Link href="/sign-in">Sign-In</Link>

          <br />
          <Link className="btnhome" href="/">Home</Link> 
          </nav>
          <UserButton />
          <Home />
          {children}
          <Button />
     
        </body>
      </html>
    </ClerkProvider>
  );
}
